{TWITTER_KEY: 'jSnvkmgfj7RjXiwDbOHA',
TWITTER_SECRET: '96B3g5qC79gnmeaOwH4iQdWuCWR4aGZEPo97d7SvAY',
OAUTH_TOKEN: '13936852-C1NH8z373oC2EuGYkWHgvYqjpw4IVOUN02tuqkSer',
OAUTH_TOKEN_SECRET: 'MD6PhXtq1MiMWR3YJs1IWyITfowIni0zPvZWKYv5Fb5Ss'}
